### ISSUE TITLE
1.4.0-beta.1中源码自带quickstart启动报错

### ISSUE THREAD

**Issue by Jackson-Yuan** [polarismesh/polaris-java-agent#107]
**Describe the bug**
![javaagent](https://github.com/polarismesh/polaris-java-agent/assets/27907161/35f07c6b-d7e7-43a4-841f-ff53fb3ebf3e)

**To Reproduce**
Steps to reproduce the behavior.
使用quickstart启动报错

**Expected behavior**
运行成功

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]
 1.4.0-beta.1

**Additional context**

**Comment by chuntaojun** [comment]
already fix in 1.5.0-beta
