### ISSUE TITLE
sct依赖的polarisSdk 1.10.1 版本和polaris-all 1.13.0版本不匹配

### ISSUE THREAD

**Issue by Jackson-Yuan** [polarismesh/polaris-java-agent#108]
**Describe the bug**
![javaagent2](https://github.com/polarismesh/polaris-java-agent/assets/27907161/7ffac9a3-b5a0-484c-83e9-f37d758e48dd)

**To Reproduce**
Steps to reproduce the behavior.
pom.xml中polarisSdk版本不一致

**Expected behavior**
版本匹配且升级到最新版
**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]
1.4.0-beta.1
**Additional context**

**Comment by chuntaojun** [comment]
需要调整 polaris-java-agent 的 sct 版本支持为 https://github.com/Tencent/spring-cloud-tencent/tree/1.12.5-2020.0.6

**Comment by chuntaojun** [comment]
already fix in 1.5.0-beta
